version: '3.8'

services:
  
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  kibana:
    image: kibana:7.8.0
    container_name: kib
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elastic
networks:
  elastic:
    driver: bridge
    # default MTU size in docker-compose is 1500
    driver_opts:
      com.docker.network.driver.mtu: 1440
